# Generated by Django 4.1.1 on 2023-02-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_rename_classroom_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
