# Generated by Django 4.1.1 on 2023-02-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_calendar", "0002_room_hasprojector_room_islab"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="committee_id",
            new_name="committee",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="class_id",
            new_name="room",
        ),
    ]
