# Generated by Django 4.1.1 on 2023-02-04 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_calendar", "0003_rename_committee_id_event_committee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registrations",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(-1),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
